## Python Assignments

In [2]:
#importing all libraries
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

### Numpy Assignment


In [51]:
#1. Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:  
#  a. Calculate the sum, mean, median, and standard deviation of the elements in the array.  
#   b. Find the indices of elements greater than 10 in the array.

integer = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(integer)
sum_val = integer.sum()
print('Sum of all integers from 1 to 20 is:',sum_val)
mean_val = integer.mean()
print('Mean of integers from 1 to 20 is:',mean_val)
median_val = np.median(integer)
print('Median of integers from 1 to 20 is:',median_val)
sd_val = integer.std()
print('Standard Deviation of all integers from 1 to 20 is:',sd_val)

indices = np.where(integer > 10)
print('Indices > 10', indices)

# 2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.  
#   a. Print the array.  
#   b. Find the transpose of the array.  
#   c. Calculate the row-wise and column-wise sums of the array.

array_1d = np.arange(1,17)
array_2d = array_1d.reshape(4,4)
print('2D array ranging from 1 to 16\n',array_2d)

transpose_val = np.transpose(array_2d)
print('Transpose of 2D array:\n', transpose_val)

colomn_wise_sum = np.sum(array_2d, axis=0 )
print('Column wise sum of array:\n',colomn_wise_sum)

row_wise_sum = np.sum(array_2d, axis=1)
print('Row wise sum of array:\n',row_wise_sum)

# 3. Create two 3 X 3 arrays filled with random integers between 1 and 20.  
#   a. Perform element-wise addition, subtraction, and multiplication.  
#   b. Compute the dot product of the two arrays.

array1 = np.random.randint(1,21, size=(3,3))
array2 = np.random.randint(1,21, size=(3,3))
print('2D array with random integer ranging from 1 to 20\n',array1)
print('2D array with random integer ranging from 1 to 20\n',array2)


addition = array1 + array2
substraction = array1 - array2
multiplication = array1 * array2

print('Element wise addition:\n', addition)
print('Element wise substraction:\n', substraction)
print('Element wise multiplication:\n', multiplication)

dot_product = np.dot(array1, array2)
print('Dot product of array1 and array2\n',dot_product)

# 4. Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns.

array1d = np.arange(1,13)
print('1D array of size 12:0', array1d)
array2d = array1d.reshape(3,4)
print('Reshaped 1D array into 3x4 2D array:\n', array2d)

sliced_array = array2d[:2, -2:]
print('Sliced array (first two column & last two rows:)\n',sliced_array)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum of all integers from 1 to 20 is: 210
Mean of integers from 1 to 20 is: 10.5
Median of integers from 1 to 20 is: 10.5
Standard Deviation of all integers from 1 to 20 is: 5.766281297335398
Indices > 10 (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)
2D array ranging from 1 to 16
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose of 2D array:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Column wise sum of array:
 [28 32 36 40]
Row wise sum of array:
 [10 26 42 58]
2D array with random integer ranging from 1 to 20
 [[ 3  4 19]
 [ 6  5  8]
 [ 7 18 13]]
2D array with random integer ranging from 1 to 20
 [[14  5 14]
 [11 13 14]
 [ 2 18 13]]
Element wise addition:
 [[17  9 33]
 [17 18 22]
 [ 9 36 26]]
Element wise substraction:
 [[-11  -1   5]
 [ -5  -8  -6]
 [  5   0   0]]
Element wise multiplication:
 [[ 42  20 266]
 [ 66  65 112]
 [ 14 324 169]]
Dot product of array1 and array2
 [[124 